version: 2.4

services:
  ci:
    #image params:
    build: .
    image: george0506/ci_cd_test_with_v_tty:latest

    #container params:
    name: ci_cd_test_container_with_v_tty

    # "-it" analog in console  
    stdin_open: true
    tty: true
  
    volumes:
      - ~CI-CD-LEARNING-REPO/src/test.cpp:/root/user/ci_cd_test/src/test.cpp

    working_dir: /root/user/ci_cd_test
    
    command: bash

    command: g++ src/test.cpp -o test && ./test
