version: '2.4'

services:

  cppcheck:
    build: .
    image: george0506/ci_cd_project:latest

    container_name: cppcheck_container
    
    command: cppcheck --enable=all --error-exitcode=1 -I./include main.cpp src/app.cpp


  ci_unit_tests:
    #image params:
    build: .
    image: george0506/ci_cd_project:latest

    #container params:
    container_name: ci_unit_tests_container

    command: ./test_executable


  ci_app:
    build: .
    image: george0506/ci_cd_project:latest

    container_name: ci_app_container
    
    command: ./app_executable 
